apiVersion: v2
type: application
name: sftpgo
version: 0.5.1
appVersion: 2.0.4
kubeVersion: ">=1.16.0-0"
description: Fully featured and highly configurable SFTP server with optional FTP/S and WebDAV support.
keywords:
  - sftp
  - ftp
  - webdav
home: https://github.com/drakkan/sftpgo
sources:
  - https://github.com/drakkan/sftpgo
  - https://github.com/sagikazarmark/helm-charts/tree/master/charts/sftpgo
maintainers:
  - name: sagikazarmark
    email: mark.sagikazar@gmail.com
    url: https://sagikazarmark.hu
annotations:
  artifacthub.io/changes: |
    - Rename ConfigMap to the release full name
  artifacthub.io/images: |
    - name: sftpgo
      image: ghcr.io/drakkan/sftpgo:v2.0.4
    - name: sftpgo-alpine
      image: ghcr.io/drakkan/sftpgo:v2.0.4-alpine
