{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "rabbitmq-operator.fullname" . }}
  labels:
    {{- include "rabbitmq-operator.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.podMonitor.interval }}
  selector:
    matchLabels:
      {{- include "rabbitmq-operator.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
